#!/usr/bin/env bash
script_dir=`dirname $0`
source $script_dir/vars

img_path=$script_dir/ubuntu.img

echo Installing dependencies...
pkg update
pkg install qemu-utils qemu-common qemu-system-x86_64-headless wget

if [[ ! -f $img_path ]]
then
  echo Downloading ubuntu cloud image...
  # https://cloud-images.ubuntu.com/minimal/releases/focal/release/
  # https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
  # https://stackoverflow.com/questions/29137679/login-credentials-of-ubuntu-cloud-server-image
  wget -O $img_path $ubuntu_img_url
  qemu-img resize $img_path $img_size
fi

$script_dir/start-vm
