#!/usr/bin/env bash
script_dir=`dirname $0`
source $script_dir/vars

# enable root-repo for docker CLI package
echo Enabling root-repo...
pkg install root-repo
pkg update

echo Installing docker...
pkg install docker

echo Creating docker context docker-in-android for SSH access
docker context create \
    --docker host=ssh://ubuntu@localhost:$host_ssh_port \
    --description="Docker-in-Android Remote" \
    docker-in-android

echo Switching to docker-in-android context...
docker context use docker-in-android
