#!/usr/bin/env bash
script_dir=`dirname $0`
source $script_dir/vars

echo Starting VM...
echo
echo mem: $mem
echo cpus: $cpus
echo
qemu-system-x86_64 -machine q35 -m $mem -smp cpus=$cpus -cpu qemu64 \
  -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
  -drive file=cloudinit.img,if=virtio,format=raw,read-only=on \
  -netdev user,id=n1,hostfwd=tcp::$host_ssh_port-:22 -device virtio-net,netdev=n1 \
  -nographic \
  -virtfs local,path=$script_dir/bind,mount_tag=host0,security_model=mapped,id=host0  \
  $script_dir/ubuntu.img

